### ISSUE TITLE
打开软件后一片空白

### ISSUE THREAD

**Issue by alanjustalan** [lencx/nofwl#7]
系统是win11，电脑型号是联想拯救者R2020 ，15.6寸笔记本。

![image](https://user-images.githubusercontent.com/42884681/229013431-7b1ab95a-e829-43ab-bc16-a7e5e050d8f8.png)

**Comment by lencx** [comment]
你在帮助菜单里点击开发者工具，看一下有没有报错信息

**Comment by alanjustalan** [comment]
> 你在帮助菜单里点击开发者工具，看一下有没有报错信息

![image](https://user-images.githubusercontent.com/42884681/229024615-e881b98a-d3ab-40aa-8eff-b66dbdacf20b.png)
刚才试过成功过一次，但关掉重新打开两次，又是空白

**Comment by alanjustalan** [comment]
> 你在帮助菜单里点击开发者工具，看一下有没有报错信息

main-6e5ac753.js:67 
        
       Error: Minified React error #311; visit https://reactjs.org/docs/error-decoder.html?invariant=311 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at oS (main-6e5ac753.js:65:20422)
    at Object.useState (main-6e5ac753.js:65:27204)
    at Mt.useState (main-6e5ac753.js:9:6382)
    at Lg (main-6e5ac753.js:76:6750)
    at F_e (main-6e5ac753.js:226:29273)
    at zN (main-6e5ac753.js:65:19538)
    at IC (main-6e5ac753.js:67:3139)
    at WB (main-6e5ac753.js:67:44817)
    at YB (main-6e5ac753.js:67:39774)
    at aQ (main-6e5ac753.js:67:39702)
AC @ main-6e5ac753.js:67
main-6e5ac753.js:67 
        
       Uncaught Error: Minified React error #311; visit https://reactjs.org/docs/error-decoder.html?invariant=311 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at oS (main-6e5ac753.js:65:20422)
    at Object.useState (main-6e5ac753.js:65:27204)
    at Mt.useState (main-6e5ac753.js:9:6382)
    at Lg (main-6e5ac753.js:76:6750)
    at F_e (main-6e5ac753.js:226:29273)
    at zN (main-6e5ac753.js:65:19538)
    at IC (main-6e5ac753.js:67:3139)
    at WB (main-6e5ac753.js:67:44817)
    at YB (main-6e5ac753.js:67:39774)
    at aQ (main-6e5ac753.js:67:39702)

**Comment by Swinden** [comment]
可以试试暗黑模式，可以显示
