### ISSUE TITLE
blank screen

### ISSUE THREAD

**Issue by Bartosh-s** [lencx/nofwl#98]
main-6e5ac753.js:67  Error: Minified React error #311; visit https://reactjs.org/docs/error-decoder.html?invariant=311 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by Bartosh-s** [comment]
this happens when i run it on windows, after using F5 few times it loads correctly.

**Comment by Axuchuanwei** [comment]
I installed it with a white screen,

**Comment by Axuchuanwei** [comment]
Request failed with status code 429

**Comment by Devesh-N** [comment]
> this happens when i run it on windows, after using F5 few times it loads correctly.

Works!

**Comment by davidsky20201101** [comment]
Using F5 works for me too, but it requires A LOT OF CLICK !!!!!!! A LOT !!!!!

**Comment by MojoCreator** [comment]
Confirm, F5 solves the issue forcing Edge to refresh. Closing it down and starting it again brings up the white screen of death again. Once a refresh works, DevTools shows 0 errors. 

Core error states it could be a React bug:
`Should have a queue. This is likely a bug in React. Please file an issue.`

**NoFWL Log**
```
[2023-07-11][18:21:08][utils::fs][INFO] file_read: C:\Users\User5.DOMAIN\.nofwl\nofwl.conf.json
[2023-07-11][18:21:08][utils::global_shortcut][INFO] global_shortcut: `Cmd+Shift+N`
[2023-07-11][18:21:08][utils::global_shortcut][INFO] global_shortcut_register
[2023-07-11][18:21:08][utils::global_shortcut][ERROR] global_shortcut_register_error: Unable to register accelerator with `RegisterHotKey`.
```

**NoFWL DevTools Error**
```
main-6e5ac753.js:76  react-i18next:: You will need to pass in an i18next instance by using initReactI18next
Are @ main-6e5ac753.js:76

main-6e5ac753.js:67  Error: Minified React error #311; visit https://reactjs.org/docs/error-decoder.html?invariant=311 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at oS (main-6e5ac753.js:65:20422)
    at Object.useState (main-6e5ac753.js:65:27204)
    at Mt.useState (main-6e5ac753.js:9:6382)
    at Lg (main-6e5ac753.js:76:6750)
    at A_e (main-6e5ac753.js:226:19977)
    at zN (main-6e5ac753.js:65:19538)
    at Y0 (main-6e5ac753.js:67:1571)
    at WB (main-6e5ac753.js:67:46017)
    at YB (main-6e5ac753.js:67:39774)
    at aQ (main-6e5ac753.js:67:39702)
AC @ main-6e5ac753.js:67
main-6e5ac753.js:67  Uncaught Error: Minified React error #311; visit https://reactjs.org/docs/error-decoder.html?invariant=311 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at oS (main-6e5ac753.js:65:20422)
    at Object.useState (main-6e5ac753.js:65:27204)
    at Mt.useState (main-6e5ac753.js:9:6382)
    at Lg (main-6e5ac753.js:76:6750)
    at A_e (main-6e5ac753.js:226:19977)
    at zN (main-6e5ac753.js:65:19538)
    at Y0 (main-6e5ac753.js:67:1571)
    at WB (main-6e5ac753.js:67:46017)
    at YB (main-6e5ac753.js:67:39774)
    at aQ (main-6e5ac753.js:67:39702)
```
Temporary Solution
Put a Force Refresh in the main menu under help or fix the bug.
